### ISSUE TITLE
Vim-xkbswitch conflicts with delimitMate

### ISSUE THREAD

**Issue by myshov** [lyokha/vim-xkbswitch#20]
[DelimitMate](https://github.com/Raimondi/delimitMate) - this is a very popular plugin for automatically closing pairs of chars (`'`, `"`, `[`, `(`) and it does other realted stuff.
 
I was trying to install it and find out that delimitMate cause insertion chars `'`, `[` and `]`instead of `э`, `х` and `ъ` resprectively. When I troubleshooted that problem I found out that without vim-xkbswitch being loaded this plugin works without errors.

Is it problem of vim-xkbswitch or delimitMate itself?

By the way here is realated issue from delimitMate's repository, hope it helps maybe https://github.com/Raimondi/delimitMate/issues/13

**Comment by lyokha** [comment]
This happens because delimitMate defines its own Insert mode mappings for those symbols and vim-xkbswitch *translates* them to appropriate symbols from Russian keyboard layout. The easiest way to fix it is to define

```vim
let g:XkbSwitchSkipIMappings = {'*'   : ["'", '"', '[', '(']}
```

in .vimrc. See also README to vim-xkbswitch where a similar issue with omnicompletion is given as an example.

**Comment by myshov** [comment]
Thank you! It works!
