### ISSUE TITLE
Time lag when switching to normal mode with russian layout

### ISSUE THREAD

**Issue by CptnGreen** [lyokha/vim-xkbswitch#37]
When i switch to normal mode (by pressing esc) from insert mode with russian layout not switched to english there is a short but unpleasant time lag (about one second) before i can use normal mode command (not switching to english manually). 

I use Ubuntu 18.04 LTS with i3-wm, PC: thinkpad yoga s1

**Comment by lyokha** [comment]
I never experienced that because I always used

```vim
set timeout timeoutlen=1000 ttimeoutlen=50
```

You can put it in your `.vimrc`. The key trick is setting small `ttimeoutlen`, i.e.

```vim
set ttimeoutlen=50
```

is enough to remove the time lag in your case. See `:help ttimeout` and `:help ttimeoutlen`.

I am going to add your case in the *Troubleshooting* section of *README*.

**Comment by CptnGreen** [comment]
Thank you for quick response! Now everything works fine
